site_name: PCLAP Docs
nav:
  - Home: index.md
  - TChem: tchem_index.md
  - PartMC: partmc_index.md
  - E3SM: e3sm_index.md
  - SCREAM: scream_index.md
theme: windmill
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascript/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
